### ISSUE TITLE
fedgis / dcdevsummit feedback

### ISSUE THREAD

**Issue by jgravois** [jgravois/presentations#1]
the first Intro to Esri Leaflet presentation went pretty good, but i should have focused more on running and discussing the one page samples in depth while the API is hosted on CDN.

i got sidetracked trying to show people how to clone the repo, install the NPM dependencies and run grunt tasks to build, test etc.  

this would have been better suited for an advanced session.

**Comment by jgravois** [comment]
cc @kneemer

**Comment by kneemer** [comment]
How long was the presentation?  I think it makes sense to just use the CDN version and just focus on using the built version.

**Comment by jgravois** [comment]
it was only 45 minutes so we'll have a little more time to play around in Palm Springs.  i just get really excited about showing people that its not just the API thats Open Source (ie: the website, the test suite etc. etc.)

**Comment by jgravois** [comment]
stepping through the code of at least one of the samples, setting breakpoints and inspecting variables in both the page source and API source is a must.

**Comment by kneemer** [comment]
I get excited about the Open Source nature of it too!
